name: emception

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: jprendes/emception
      - name: Build emception
        run: ./build-with-docker.sh
      - name: Archive build artifacts
        run: zip -r emception.zip build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: emception-build
          path: emception.zip
